services:
  spark:
#    image: datamechanics/spark:3.2.1-latest
    image: apache/spark:latest
#    image: apache/spark:v3.1.3
    container_name: spark
    hostname: spark
  #  command: /opt/spark/bin/spark-shell  --conf spark.jars.ivy=/tmp/.ivy --master local[1]
  #  command: driver --conf spark.jars.ivy=/tmp/.ivy --master local[1]
  #  command: /opt/spark/sbin/start-master.sh
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.master.Master -h 0.0.0.0 -p 7077
    environment:
      SPARK_DRIVER_BIND_ADDRESS: "0.0.0.0"
    ports:
      - "8080:8080"
      - "7077:7077"
#    volumes:
#      - /Users/esm/workspaces/beam-test:/opt/spark/logs:rw

  beam-jobserver:
    image: apache/beam_spark_job_server:2.41.0
    container_name: beam
    hostname: beam
    command: --spark-master-url=spark://spark:7077
    ports:
      - "8098:8098" # ArtifactStagingService
      - "8097:8097" # Java ExpansionService
      - "8099:8099" # JobService
#    volumes:
#      - /Users/esm/workspaces/beam-test/logging.properties:/logging.properties
